INSERT INTO translations (locale, column_name, value, value_json, translatable_id, translatable_type) VALUES
('de', 'value_json', NULL, '<div class=\"mega_topic\">
<h1>Geschichte Samarkands</h1>
<h3>Geschichte Samarkands: 2500 Jahren Alt</h3>
<p>Schöne und sehr traurige Legende erklärt den Grund, warum die Stadt Samarkand so genannt wurde. Die Geschichte über zwei Geliebte, Junge und Mädchen desselben Alters. Das Mädchen, das Kant (\"Zucker\")heißte und sie wie eine Prinzessin war, hat den Jungen Samar getroffen, und sie haben sich schließlich in einander verliebt. Als der reiche und mächtige Vater von Kant gewusst hat, dass Samar aus der armen Familie ist, hat er die Möglichkeit ihrer Ehe abgelehnt und hat der Vater von Kant den Jungen getötet. Als Kant erkannt hatte, dass ihr Geliebter tot ist, tötet sie sich (sie sprang aus dem Schlossdach). Überwältigt mit der Schwermut dieser Geschichte haben Menschen beschlossen, der Stadt einen neuen Namen gegeben (nach Samar und Kant). Der Name wurde Samarkand und die Legende dieser Liebe lebt noch.</p>
<p>In der Geschichte der Welt ist Samarkand dem Phönix ähnlich: Samarkand war durch viele Angriffe und Kriege zerstört aber wurde jedes Mal von der Asche aufgebaut. Die Erde von Samarkand hat so viele ermüdende Kämpfe überlebt aber die Stadt steht noch ruhmvoll, glänzend und schön; und die Geschichte Samarkands ist mehr als 2500 Jahren begonnen, jedes Jahr ist von wichtigen Ereignissen voll.</p>
<p>Nachdem Samarkand auf dem Berg Afrosiab gebaut war,(sein alter Name war Marakanda), wachste Samarkand im sehr schnellen Tempo mit Basaren und Moscheen. Als Alexander der Große seinen Angriff begonnen hatte, war Samarkand bereits gut entwickelte Stadt mit der großen Bevölkerung; Handwerke, Kultur und Handel waren auf dem hohen Niveau. Diese blühende Stadt ist in Ruinen in 328 v. Chr. während des Aufstandes gegen Alexander den Großen gefallen, und das war nicht die letzte Heimsuchung in der Geschichte Samarkands.</p>
<h2>Die Geschichte Samarkands in den Tagen der Seidenstraße</h2>
<div class=\"photos_line left_margin\"><a title=\"Die Geschichte Samarkands in den Tagen der Seidenstraße\" href=\"http://www.people-travels.com/images/gallery/samarkand/34.jpg\" rel=\"lightbox-1\"><img title=\"Die Geschichte Samarkands in den Tagen der Seidenstraße\" src=\"http://www.people-travels.com/images/gallery/samarkand/34.jpg\" alt=\"Die Geschichte Samarkands in den Tagen der Seidenstraße\" width=\"550\" height=\"413\" border=\"0\" /></a></div>
<p>Zum Glück war gute geografische Position nicht nur ein Fluch, sondern auch ein Geschenk für Samarkand. Die Stadt war sehr wichtig für die Seidenstraße; sie hat die ersten Chinesen als der Teil des Persers (Achemenid) Reich begrüßt, und war natürlich die Straßenkreuzung und das Zentrum des Handels in der Welt. Im 16. Jahrhundert haben die Seewege zwischen Asien und Europa verbunden, dann die Wichtigkeit der Seidenstraßen wurde herabgesetzt. Aber in der Geschichte der Welt bleibt Samarkand das Herz der Seidenstraßen.</p>
<p>Das 8. Jahrhundert ist sehr wichtige Zeit des Lebens Samarkands; die Stadt wurde von den Arabern erobert, die den Islam gebracht haben (der bald Hauptreligion wurde). Es war ein Zeitalter der nomadischen Angriffe. Das war die Zeit, als Seljuks, Khara-Kitais und andere versucht haben, die Macht zu haben. Aber nur mit dem mongolischen Angriff hat Samarkand verstanden, was der echte Terror bedeutet.</p>
<p>Für die Geschichte Samarkands war der Angriff von Genghis Khan eine schreckliche Heimsuchung. Horden dieses grausamen Mannes haben im Jahre 1220 das Bewässerungssystem zerstört, Wasser war verschmutzt. Alle Genghis Khan Handlungen waren nichts als ein schreckliches Gemetzel, das Tausende Leben gebracht hat. Es war ein größter Schritt zurück für Samarkand. Aber die Stadt hat sich bald regeneriert. Schon im Jahre 1933 hat Ibn-Batutta gezeugt, der sehr berühmter Reisender war, dass Samarkand ist größte und auch schönste Stadt, die er jemals gesehen hatte.</p>
<p>Aber der echte Anstieg Samarkands war in den Zeiten, als Tamerlane an die Macht gekommen ist und Samarkand die Hauptstadt seines Reiches gemacht hat. Während seiner Regierung in Jahren 1372-1402 sendete Tamerlane besten Handwerkern und Architekten nach Samarkand, um es schöner zu machen. Die Straßen der Stadt wurden wie die entfernten Städte auf dem Weg von Tamerlane genannt. Tamerlane befahl, Samarkand mit schönen Gebäuden aufbauen; einer von ihnen ist Moschee von Bibi Khanum, die kolossal und mit dem geometrischen Bild geschmückt ist. Ein anderes großes Gebäude Gur Emir Mausoleum wurde vor dem Tod von Tamerlane gebaut und ist die Grabstätte für Ihn und alle Mitglieder seiner Dynastie einschließlich Ulugbek (der populärsten Enkel von Tamerlane) geworden. Der Beitrag von Ulugbek ins kulturelle und wissenschaftliche Leben Samarkands war unbezahlbar. Er befahl, um Sternwarte zu bauen, die die beste Sternwarte jener Tage war. Ulugbek auch, wie sein Urgroßvater, hat vielen Wissenschaftlern zu seiner Stadt gebracht.</p>
<div class=\"photos_line left_margin\"><a title=\"Moderne Geschichte Samarkands\" href=\"http://www.people-travels.com/images/gallery/samarkand/24.jpg\" rel=\"lightbox-1\"><img title=\"Moderne Geschichte Samarkands\" src=\"http://www.people-travels.com/images/gallery/samarkand/24.jpg\" alt=\"Moderne Geschichte Samarkands\" width=\"550\" height=\"367\" border=\"0\" /></a></div>
<p>Die 14. und 15. Jahrhunderte waren die Zeiten der großen Rekonstruktion Samarkands, so genanntes \"Goldenes Zeitalter\" dieser heroischen Stadt; Neue schöne Straßen, neue Architektur-Ensembles wurden gebaut.</p>
<h2>Moderne Geschichte Samarkands</h2>
<p>Während der Periode von 1929 bis 1930 war Samarkand die Hauptstadt der usbekischen sowjetischen Republik. Heute ist Samarkand in der Liste von ältesten Städten in der Welt, und auch der zweiten großen multinationalen Stadt in Usbekistan, mit atemberaubender Architektur, die durch UESCO als Erbe der Menschheit gekennzeichnet ist. Diese Stadt ist auch das Zentrum des Tourismus Usbekistans, die die Gäste aus aller Welt anzieht.</p>
<p><em>Samarkand mit Ihren eigenen Augen zu sehen und den Geist von alten zu fühlen, sind so leicht: bestellen Sie jetzt die Tour nach Usbekistan von Peopletravel! Es ist Zeit, um eine der bemerkenswertesten und aufregenden Reise in Ihrem Leben zu machen!</em></p>
</div>[[$SmartargetWhatsappContactUs]]', 1, 'App\Models\City'),
('es', 'value_json', NULL, '<div class=\"mega_topic\">
<h1>La historia de Samarcanda</h1>
<h3>Historia de Samarcanda: tiniendo 2500, sigue andando</h3>
<p>Leyenda hermosa y muy triste explica la razón por que Samarcanda ciudad se llamaba así. La historia es sobre dos enamorados chico y chica de misma edad. La chica que tenia un nombre bello Kant (\"azúcar\") y que era en realidad la princesa conoció al chico quien se llamó Samar y que finalmente se enamoró de uno al otro. Pero cuando rico y poderoso padre de Kant sabía que Samar venia de la familia pobre, rechazó la posibilidad de su matrimonio. A la inverso el padre de Kant mató al chico. Cuando Kant descubrio que su amante estaba muerto, Samar se suicidó al saltar desde el tejado del castillo. Abrumado por la tristeza de esta historia, la gente tomó una decisión y dio a la ciudad un nuevo nombre, dedicada al chico y la chica. El nombre era Samarcanda, y la leyenda de este amor todavía vive.</p>
<p>En la historia mundial Samarcanda parece a un fénix: lo que solía ser destruido por las invasiones y guerras, pero sobrevivió cada vez renaciendo de las cenizas. La tierra de Samarcanda conocía muchas batallas agotadoras, pero la ciudad sigue ser glorioso, brillante y hermoso, y la historia de Samarcanda se inició hace más de 2500 años atrás, marcando cada año con eventos importantes.</p>
<p>Una vez al encontradose en el Monte Afrosiab, la ciudad de Samarcanda (su antiguo nombre era Marakanda) creció en el tempo muy rápido, convirtiéndose a la gran ciudad con bazares y mezquitas. Al momento de inicio de la invasión de Alejandro Magno, Samarcanda ya habia sido bien desarrollada con gran población; la artesanía, la cultura y el comercio estaban en alta nivel. Esta floreciente ciudad cayó en ruinas en el año 328 AC durante el levantamiento contra Alejandro Magno, y esto no era la último caso en la historia de Samarcanda.</p>
<h2>Historia de Samarcanda en la época de la Ruta de Seda</h2>
<div class=\"photos_line left_margin\"><a title=\"Historia de Samarcanda en la época de la Ruta de Seda\" href=\"http://www.people-travels.com/images/gallery/samarkand/34.jpg\" rel=\"lightbox-1\"><img title=\"Historia de Samarcanda en la época de la Ruta de Seda\" src=\"http://www.people-travels.com/images/gallery/samarkand/34.jpg\" alt=\"Historia de Samarcanda en la época de la Ruta de Seda\" width=\"550\" height=\"413\" border=\"0\" /></a></div>
<p>Pero por suerte, buena ubicación geográfica no era sólo una maldición, pero también un regalo para Samarcanda. La ciudad obtuvo gran importancia para la Ruta de Seda; el dio la bienvenida a primeros chinos que habian parte del Imperio Persa (Achemenid) y muy pronto se convirtió naturalmente en el cruce de caminos y el centro de comercio mundial. En el siglo 16 las rutas marítimas conectaron Asia y Europa, así como la importancia de la Ruta de Seda se bajó. Pero en la historia mundial para la eternidad Samacanda seguirá siendo el corazón de la Ruta de Seda.</p>
<p>El siglo 8 era un tiempo muy importante en la vida de Samarcanda: fue conquistado por los árabes quienes llevaron el Islam (que luego se convirtió a la religión principal). Hubo una época de diferentes invasiones por nómadas, el tiempo cuando Seljuk, Khara Kitais y otros trataron obtener el poder. Pero sólo con la invasión de los mongoles Samarcanda descubrio como era el terror verdadero.</p>
<p>Para la historia de Samarcanda la invasión de Genghis Khan era un suplicio horrible para salir adelante. Hordas de este hombre cruel en 1220 destruieron el sistema de riego, estropearon el agua. Todas las acciones de Genghis Khan no eran más que una horrible masacre que llevó miles de vidas. Esto fue un paso más grande atras para Samarcanda. Pero la ciudad pronto regenerado. Ya en 1933 Ibn-Batutta, el viajero muy famoso fue testigo de Samarcanda era muy grande y también la ciudad más hermosa que había visto antes.</p>
<p>Sin embargo, el aumento real de Samarcanda fue en los tiempos en que Tamerlán llegó al poder y la convirtió en la capital de su imperio, que era muy grande y se amplió hasta Bosfor. Durante sus campañas en 1372-1402 los mejores artesanos y arquitectos fueron recogidos por Tamerlán y llevados a Samarcanda para hacerla más bella. Las calles de la ciudad fueron nombradas como las ciudades distantes por el camino de Tamerlán. Tamerlán ordenó construir en Samarcanda los hermosos edificios, uno de ellos era la mezquita de Bibi Khanum, monumental y decorado con un patrón geométrico. Otro gran estructura Gur Emir Mausoleum fue construido antes de la muerte de Tamerlán y se convirtió en la tumba para él mismo y para todos los miembros de su dinastía, incluyendo Ulugbek que fue uno de los nietos más populares de Tamerlán. La contribución Ulugbek hecho en la vida cultural y científica de Samarcanda era inestimable. El ordenó la construcción del Observatorio, que fue el observatorio más perfecto de esos días. Ulugbek también, como su bisabuelo, llevó muchos científicos a su ciudad.</p>
<div class=\"photos_line left_margin\"><a title=\"La historia de Samarcanda moderna\" href=\"http://www.people-travels.com/images/gallery/samarkand/24.jpg\" rel=\"lightbox-1\"><img title=\"La historia de Samarcanda moderna\" src=\"http://www.people-travels.com/images/gallery/samarkand/24.jpg\" alt=\"La historia de Samarcanda moderna\" width=\"550\" height=\"367\" border=\"0\" /></a></div>
<p>Los siglos 14 y 15 fueron los tiempos de la gran reconstrucción de Samarcanda, llamada \"Edad de Oro\" de esta heroica ciudad, inmortalizado en la historia de Samarcanda con la construcción del muro alrededor de Samarcanda. Nuevas calles empedradas se extendían a lo largo de la ciudad, nuevos conjuntos de arquitectura fueron construidos.</p>
<h2>La historia de Samarcanda moderna</h2>
<p>Durante el período de 1929 a 1930 Samarcanda fue la capital de la República Soviética de Uzbekistán. Hoy Samarcanda se encuentra en la lista de las ciudades más antiguas del mundo y también la segunda ciudad grande multinacional de Uzbekistán, centro de la cultura y la arquitectura impresionante, marcado por UESCO como patrimonio de la humanidad. Esta ciudad es también el centro de Uzbekistán turismo, que atrae a visitantes de todo el mundo.</p>
<p><em>Para ver Samarkanda con sus propios ojos y sentir el espíritu de la antigudad es muy fácil: bastante reservar el viaje a Uzbekistán atravez de Peopletravel! Es la hora de hacer uno de los viajes más sorprendentes y excitantes de su vida!</em></p>
</div>[[$SmartargetWhatsappContactUs]]', 1, 'App\Models\City'),
('ru', 'value_json', NULL, '<div class=\"mega_topic\">
<h1>История Самарканда</h1>
<h3>История Самарканда: городу более 2700 лет, и он все еще существует</h3>
<p>Причиной названия города объясняет очень грустная легенда, и она гласит, что было два молодых человека, юноша и девушка одного возраста. Девушка, по имени Канта (\"сахар\"), а она была фактически принцесса, встретила юношу, по имени Самар и они полюбили друг друга с невероятной силой. Но когда отец Канты узнал, что Самар происходит из бедной семьи, он отверг возможность их брака и убил юношу. Когда Канта узнала, что ее возлюбленный мертв, она убивает себя, прыгая с крыши замка. Переполненные печалью этой истории, люди приняли решение и дали городу новое имя Самарканд, и посвятили еговозлюбленным. Эта легенда до сих пор живет в сердцах людей.</p>
<p>История Самарканда началась более чем 2700 лет назад, отмечая каждый год с важными событиями. В истории Самарканда было множество вражеских вторжений,истощающих сражений и войн, которые пытались уничтожить город, но каждый раз город возрождался вновь, и все еще стоит, славный, блестящий и прекрасный.</p>
<p>Город Самарканд (его старое название было Mараканда) расположено на горе Aфросиаб, развивался в очень быстром темпе, став большим городом с базарами и мечетями. Самарканд являлся уже хорошим развитым и укрепленным городом с большим населением, ремесленничество, культура и торговля была на высоком уровне. И этот процветающий город был завоеван в 328 до н.э. Александром Македонским, и это не было последним тяжелым испытанием в истории Самарканда.</p>
<h2>История Самарканда, времена Великого Шелкового Пути</h2>
<div class=\"photos_line left_margin\"><a title=\"Samarkand history in the days of the Great Silk Road\" href=\"images/gallery/samarkand/34.jpg\" rel=\"lightbox-1\"><img title=\"Samarkand history in the days of the Great Silk Road\" src=\"images/gallery/samarkand/34.jpg\" alt=\"Samarkand history in the days of the Great Silk Road\" width=\"550\" height=\"413\" border=\"0\" /></a></div>
<p>К счастью хорошее географическое расположение города было не только проклятием, но и подарком для Самарканда. Город стал очень важным для Великого Шелкового Пути, он стал перекрестком и центром всемирной торговли. В 16-м столетии морские маршруты соединили Азию и Европу, и важность Великого Шелкового Пути уменьшилась. Но в истории Самарканда, Великий Шелковый Путь останется в памяти навсегда.</p>
<p>8-ое столетие - очень важное время в жизни Самарканда и в это время его завоевали Арабы, которые принесли с собой Ислам (Ислам стал главной религией). Была эра различных кочевых вторжений, время, когда многие пытались захватить власть. Но только с вторжением монголов (войска Чингизхана) Самарканд узнал, что такое - реальный террор.</p>
<p>Для Самарканда вторжение в 1220 году войск Чингизхана было ужасным и тяжелым испытанием. Орды этого жестокого правителя уничтожили ирригационную систему, и испортили воду, разграбили и почтиполностью уничтожили город. Все действия Чингизханабыли связанытолько с ужасной резней, и это был наибольший шаг назад в развитии для Самарканда. Но город скоро возродился на территории спальных и сельских районов — на месте современного Самарканда. Знаменитый путешественник Ибн-Батутта свидетельствовал, что Самарканд очень большой, а также самый прекрасный город, который он когда-либо видел.</p>
<p>Но реальное процветание Самарканда произошло во времена, когда к власти пришел Тамерлан (Амир Тимур), и сделал его столицей своей Империи, которая была действительно огромна, и расширялась вплоть до Босфора. В течение его кампаний в 1372-1402 годах он отправлял лучших мастеров и архитекторов в Самарканд для того, чтобы сделать город еще более красивым. Улицы города были назваными подобно отдаленным городам, которые встречались на пути Taмерлана. Он наказал архитекторам создать Самарканд с прекрасными зданиями и одно из них - мечеть БибиХаным, монументальное здание, украшенное геометрическим образом. Другой большой Мавзолей Эмира построен перед смертью Taмерлана и стал могилой для него и всех членов его династии, в том числе и для Улугбека, который был одним из самых любимых внуков Taмерлана. ВкладУлугбека, в развитие культурной и научной жизни Самарканда, был бесценен. Улугбек, подобно его Великому деду, привозил много ученых со всего мира. Он построил Обсерваторию, которая была совершенной обсерваторией тех дней.</p>
<div class=\"photos_line left_margin\"><a title=\"Modern Samarkand history\" href=\"images/gallery/samarkand/24.jpg\" rel=\"lightbox-1\"><img title=\"Modern Samarkand history\" src=\"images/gallery/samarkand/24.jpg\" alt=\"Modern Samarkand history\" width=\"550\" height=\"367\" border=\"0\" /></a></div>
<p>14-15-ые столетия были временами большой реконструкции Самарканда, так называемый \"Золотой Век\" этого героического города, и увековечен в Самаркандской истории созданием защитной стены вокруг Самарканда. Новые каменные вымощенные улицы простерлись вдоль городских стен, строились новых ансамбли архитектуры.</p>
<h2>Современная история Самарканда</h2>
<p>В период с 1929 по 1930 год Самарканд был столицей Узбекской Советской Социалистической Республики. Сегодня Самарканд находится в списке самых старых городов в мире, а также второй большой многонациональный город в Узбекистане, является центром культуры и архитектуры, отмечен ЮНЕСКО, как наследие человечества. Этот город - также является центром туризма, привлекающий гостей со всего света.</p>
<p><em>Чтобы посмотреть Самарканд своими собственными глазами и почувствовать дух древности, отправляйтесь в тур в Узбекистан с компанией Peopletravel! Настало время совершить одну из самых замечательных и захватывающих поездок в вашей жизни!</em></p>
</div>[[$SmartargetWhatsappContactUs]]', 1, 'App\Models\City'),
('de', 'value_json', NULL, '<div class=\"mega_topic\">
<h1>Geschichte Bucharas</h1>
<h3>Geschichte Bucharas: mehr als Jahrhunderte</h3>
<p>Buchara ist sehr alte Stadt, die in verschiedenen Zeiten das Zentrum von verschiedenen Reichen und Lieblingsort von vielen Großen Dynastien gewesen war. Deshalb ist die Geschichte von Buchara so reich und voll mit wichtigen Ereignissen . In Shahnameh (ein sehr berühmtes und ein sehr altes Gedicht auf Persisch ) ist geschrieben, dass der Gründer Bucharas König Siavash war, der der mythischen und legendären Pischdak Dynastie angehört hat. Der Hauptgrund, warum er diesen Ort für seine Stadt gewählt hat, ist die günstige Lage direkt auf der Seidenstraße mit dem warmen Klima und vielen Flüssen.</p>
<p>Aber außer den Legenden und alten Geschichten gibt es historische Ereignisse in der Geschichte von Buchara. Das Fundaments dieser Stadt wurde500 Jahr v. Chr gelegt. Bevor die Stadt gegründet wurde, war sie bereits von Leuten seit einer langen Zeit bewohnt. Die Stadt wurde in 3 Abschnitte gebaut</p>
<p>500 Jahre v. Chr. ist ein wichtiger Zeitpunkt in der Geschichte Bucharas: das ist die Zeit, als der Vasall-Staat des Großen persischen Reiches berühmt war. Später war Buchara das Zentrum für den ersten Greco-Bactrianen, und das Reich von Seleucid und natürlich auch das bekannte Reich Kuschan. In der Geschichte Bucharas wird erwähnt, dass zu dieser Zeit Buchara eine ziemlich wohlhabende Stadt war. Das alles hat die Stadt besser und reicher gemacht. Es war die goldene Zeit der Stadt. Circa 350 Jahr v. Chr. Geschichte und die Entwicklung der Stadt sind auf einem anderen Niveau wegen Stämme von Hua gesunken, die aus der Mongolei gekommen sind.</p>
<div class=\"photos_line left_margin\"><img title=\"Geschichte Bucharas: mehr als Jahrhunderte\" src=\"http://www.people-travels.com/images/mega/bukhara-history/bukhara-history_1.jpg\" alt=\"Geschichte Bucharas: mehr als Jahrhunderte\" width=\"550\" height=\"281\" border=\"0\" /></div>
<p>Bevor der Islam die Hauptreligion in Buchara wurde, gab es zwei Religionen. Den Manichäismus und das nestorianische Christentum. Aber mit dem Angriff von Arabern (nach dem blutigen und sehr ermüdenden legendären Kampf von Talas) ist der Islam ist dominierende Religion geworden .Und wie Sie wissen, ist es heute noch so.</p>
<h2>Periode von Samanid in Buchara. Geschichte Bucharas</h2>
<p>Während sich Buchara nach dem Kampf von Talas, im Jahr 850 n. Chr. an die neue Religion gewöhnt hat dieses Ereignis einen wichtigen Platz in der Geschichte Bucharas genommen : die Stadt wurde wieder die Hauptstadt eines anderen Reiches und zwar das Reich der Samanids. Die persische Sprache wurde wieder die Hauptsprache in der Stadt. Die Hauptstadt des Reiches Samanid ist und bleibt die Stadt Buchara ein intellektuelles Zentrum der Moslem-Welt. Die Stadt hat berühmter Muhammad Al-Buchari zur Welt vorgebracht, der Autor der Hadithen, die kluge authentische Aussprüche des Hellsehers Muhammad waren. Die Geschichte Bucharas hat sich wieder in 999 n. Chr. geändert, als die Dynastie von Samaniden von der Karakhaniden Dynastie abgelöst wurde. Im 13. Jahrhundert war die Zeit, als Muhammad Khorezmshakh in die Stadt gekommen ist.</p>
<p>Dann, nach Karakhanid und Periode von Khorezmshakh, war die Zeit der Mongolen in der Geschichte Buchara. Dschingis Khan hat befohlen, die Stadt nieder zu brennen, nachdem er barmherziger war, weil die Leute Bucharas bereit waren zu gehorchen. Mongolen haben bis die Zeiten von Tamerlane über die Stadt geherrscht.</p>
<p>In der Zeit Schaybaniden wurde Buchara der Feudelstaat auch genannt als Khanate Bucharas. Über Khanate Bucharas wurde von mehreren Herrschern beherrscht, als 1785 mit der Hilfe der Dynastie von Shah Murad und Manghit sich in Emirat von Buchara gewandelt hat.</p>
<div class=\"photos_line left_margin\"><img title=\"Geschichte Bucharas\" src=\"http://www.people-travels.com/images/mega/bukhara-history/bukhara-history_2.jpg\" alt=\"Geschichte Bucharas\" width=\"550\" height=\"354\" border=\"0\" /></div>
<p>Es ist bekannt, dass in der Geschichte Bucharas britischen und russischen Reichen Emirat Bucharas eine wichtige Rolle gespielt hat. Gegen Ende des 19. Jahrhunderts war die Zeit der Projektierung und dann des Konstruierens langer Trans-kaspischer Eisenbahn durch die Heilige Stadt.</p>
<p>Während der Jahre 1920-1925 in der Geschichte von Buchara gab es die Zeit der sowjetischen Republik Bucharas, die in UsSSR integriert war. Nach den Kriegen in Afghanistan und Tadschikistan sind die Flüchtlinge nach Buchara und auch Samarkand gekommen.</p>
<h2>Moderne Geschichte Bucharas</h2>
<p>Heutzutage geht die Geschichte weiter, als Buchara ein Teil des unabhängigen Usbekistans wurde. Die Stadt hat sich nicht viel geändert, Straßen und Gebäude sind genauso wie früher geblieben. Um die Atmosphäre jener Ereignisse beschreiben zu können, sollen Sie Buchara besuchen und alle seine Straßen und Architektur mit Ihren eigenen Augen sehen. Nicht viele Ereignisse der Geschichte Bucharas wurde dokumentiert. Es gibt ein Buch von Narshakhi \"Geschichte von Buchara\" in Jahr 944 vollendet hat und viele interessante Tatsachen über die alten Zeiten Bucharas geschrieben hat: tägliches Leben seiner Bürger, Gelehrten, Geschichten usw.</p>
<p>Buchara, so genannte Heilige Stadt, ist ein sehr interessanter Ort, wo Geschichte klar unddeutlich gesehen wird. Buchara hat diesen unvergesslichen Charme. Diese Stadt ist das Zentrum von vielen Reichen, sogar das Zentrum einer Großer Religion gewesen ist, sie wurde zerstört dann wieder von der Asche aufgebaut, sie hat zur Welt vielen berühmten Menschen hervorgebracht, und sie steht noch unter der warmen Sonne Usbekistans. Die Stadt begrüßt Sie, verlieren Sie Ihre Zeit nicht, bestellen Sie die Tour nach Usbekistan von Peopletravel und besuchen Sie die Heilige Stadt!</p>
<div class=\"photos_line left_margin\"><img title=\"Geschichte Bucharas\" src=\"http://www.people-travels.com/images/mega/bukhara-history/bukhara-history_3.jpg\" alt=\"Geschichte Bucharas\" width=\"550\" height=\"378\" border=\"0\" /></div>
</div>[[$SmartargetWhatsappContactUs]]', 2, 'App\Models\City'),
('es', 'value_json', NULL, '<div class=\"mega_topic\">
<h1>Historia de Bukhara</h1>
<h3>Historia de Bukhara: un visto atras por un siglos</h3>
<p>Bukhará es la ciudad muy antigua que en otros tiempos había sido el centro de los imperios diferentes y lugar favorito de muchas grandes dinastías. Por eso la historia de Bukhara es tan rica y llena de eventos importantes. Está escrito en Shahnameh (muy famoso y muy viejo poema sabio en lengua irani) que el fundador de Bukhara era el Rey con el nombre orgullo Siavash quien pertenecía a la dinastía Pishdak mítico y legendario. La razón principal por la que eligió esta tierra por su ciudad era la ubicación suerte justo en la Ruta de Seda, el clima bueno y muchos ríos.</p>
<p>Pero además de las leyendas y las buenas historias viejas, hay exactamente los factos históricos en la historia de Bukhara.De acuerdo con ellos, la fecha de fundación de esta ciudad era 500 AC. Pero antes de que la ciudad fue fundada, ya había sido habitada por la gente durante un tiempo bastante largo. La ciudad fue formado de la unión de tres asentamientos separados y la construcción del muro defendiendo por alrededor.</p>
<p>500 AC como punto muy importante en la historia de Bukhara influyo a la ciudad y el mundo: este es un tiempo exactamente cuando era famoso por ser el estado vasallo del Gran Imperio Persa. Más tarde Bukhara fue el centro del primer estado de Greco-bactrianos y el Imperio Selévkidos y por supuesto bien conocido Kushan Imperio. El facto esta mencionado en la historia de Bukhara que en aquellos tiempos Bukhara era laciudad bastante próspera. Pero al convertirse en el centro del comercio por el camino de la Ruta de Seda, la ciudad se hizo mejor y más próspero. Esos tiempos fueron la época de oro de la ciudad. Aproximadamente en 350 AC la historia de Bukhara historia y el desarrollo de la ciudad saltó a otro nivel a causa de las tribus de Hua que vinieron de Mongolia.</p>
<div class=\"photos_line left_margin\"><img title=\"La historia de Bukhara: un salto atras por los siglos\" src=\"http://www.people-travels.com/images/mega/bukhara-history/bukhara-history_1.jpg\" alt=\"La historia de Bukhara: un salto atras por los siglos\" width=\"550\" height=\"281\" border=\"0\" /></div>
<p>Antes del Islam se convirtió en la principal religión en Bukhara, hubo dos religiones allí - el maniqueísmo y el cristianismo nestoriano. Pero con el vencedor de los árabes no en seguida, sino poco a poco y con muchos años pasado (después de sangrienta y muy agotador legendaria Batalla de Talas) El Islam se convirtió en la religión dominante, y, como usted sabe, todavía se mantiene de esta manera.</p>
<h2>El periodo de Samanidos en Bukhara. Historia de Bukhara</h2>
<p>Mientras Bukhara ha sido acostumbrando a la nueva religión, con un siglo pasado después de la batalla de Talas, en el año 850 un evento más importante en la historia de Bukhara tomó su lugar: la ciudad volvió a ser la capital de otro Imperio – Imperio de Samanidos. Lengua persa volvió a ser la lengua principal de la ciudad. Siendo la capital del Imperio de Samanidos, Bukhara era floreciente ciudad y el centro intelectual del mundo musulman. La ciudad dio a luz al famoso Muhammad al-Bukhari, el autor de hadices que eran realmente sabios auténticamente dichos por Profeta Muhammad. Historia de Bukhara cambió una vez más, en el año 999, cuando la dinastía de Samanidos fue cambiado por la dinastía Karakhanidos. Al fin de siglo XIII Muhammad Khorezmshakh conquistó la ciudad.</p>
<p>Luego, después de los períodos de Karakhanidos y Khorezmshakh, Mongol epoca sucedió en la historia de Bukhara. Genghis Khan ordenó quemar casi la mitad de la ciudad, pero después él fue más misericordioso, porque el pueblo de Bukhara acordó aceptarle. Mongoles gobernaron la ciudad hasta la época de Tamerlán.</p>
<p>Despues Bukhara se convirtió en el estado feudal llamado Janato de Bukhara, en esos tiempos Shaybanidos lo gobernaron y se pronunciaron el capital. Janato de Bukhara fue gobernado por varios gobernantes cuando en el año 1785 con la ayuda de Murad Shah y la dinastía Manghit se convirtió en el Emirato de Bukhara.</p>
<div class=\"photos_line left_margin\"><img title=\"Historia de Bukhara\" src=\"http://www.people-travels.com/images/mega/bukhara-history/bukhara-history_2.jpg\" alt=\"Historia de Bukhara\" width=\"550\" height=\"354\" border=\"0\" /></div>
<p>Es bien sabido que Emirato de Bukhara desempeñado un papel muy importante en la historia de Bukhara y imperios británico y ruso. A final del siglo XIX era el momento de proyectar y luego construir largo Trans-Caspio ferrocarril a traves de la ciudad santa.</p>
<p>Durante los años 1920-1925 en la historia de Bukhara estaba el tiempo de Popular República Soviética de Bukhara, integrado en UzSSR. Más tarde, refugiados de las guerras en Afganistán y Tayikistán vinieron a Bukhara y Samarkanda también.</p>
<h2>Historia moderna de Bukhara</h2>
<p>Y ahora, en nuestros días la historia tan rica de Bukhara ciudad todavía sigue ahora cuando Bukhara se convirtió en parte de Uzbekistán independiente. La ciudad no ha cambiado mucho, las calles y los edificios son los mismos. Y para sentir el ambiente de esos acontecimientos descritos anteriormente todo lo que se necesita es visitar a Bukhara y ver todas sus calles y la arquitectura con sus propios ojos. En realidad, no muchos de los acontecimientos de la historia de Bukhara fueron documentados, pero hay libro de Narshakhi \"Historia de Bukhara\" finalmente completado en 944 y tiene muchos datos interesantes sobre los viejos tiempos de Bukhara: la vida ordinaria de sus ciudadanos, académias, historias.</p>
<p>Bukhara, llamado la ciudad santa, es un lugar muy interesante donde se puede ver la historia muy claramente. Tiene ese encanto inolvidable. Esta ciudad ha sido el centro de muchos imperios, tambien el centro de una Gran religión, fue destruido y luego construido de las cenizas de nuevo, dio al mundo muchas personas famosas, y todavía se encuentra bajo el sol cálido de Uzbekistán. La ciudad le da la bienvenida, así que no pierde el tiempo, reserva el viaje a Uzbekistán a traves de Peopletravel y visite la ciudad santa!</p>
<div class=\"photos_line left_margin\"><img title=\"Historia de Bukhara\" src=\"http://www.people-travels.com/images/mega/bukhara-history/bukhara-history_3.jpg\" alt=\"Historia de Bukhara\" width=\"550\" height=\"378\" border=\"0\" /></div>
</div>[[$SmartargetWhatsappContactUs]]', 2, 'App\Models\City'),
('ru', 'value_json', NULL, '<div class=\"mega_topic\">
<h1>История Бухары</h1>
<h3>История Бухары: назад в прошлое</h3>
<p>Бухара - очень древний город, и в различных временах был центром различных Империй и любимым местом многих из различных Династий. Вот почему история Бухары так богата различными и важными событиями. Об этом пишется в Шахнаме (Книга о Царях, древняя книга у иранцев), что основатель Бухары был Царем и гордо назвался Сиявуш, и принадлежал к мифической и легендарной Династии Пишдак. Главная причина, почему он захотел построить этот город именно в этом месте такова - удачливое расположение прямо на Великом Шелковом Пути, хороший теплый климат и много рек.</p>
<p>Но кроме легенд и старых анекдотов, есть точные исторические факты в бухарской истории. Следуя за ними, дата основания этого города 500 год до нашей эры. Но перед тем, как город был основан, это место было уже населено людьми длительное время. Город был сделан из объединения трех отдельных поселений и строительства оборонительной стены вокруг них.</p>
<p>500 год до нашей эры, очень важный пункт в истории Бухары и он сильно повлиял на город и мир: это точно время, когда этот город был знаменит, как государство вассала Большой Персидской Империи. Более поздняя Бухара была центром для первой Греко-Бактрианской, и Селевкидской Империей, конечно же, хорошо известная Империя Кушан. В бухарской истории упомянут факт, что по тем временам, Бухара была весьма преуспевающим городом. Становясь центром торговли по пути Великой Шелковой Дороги, город становился еще лучше и более преуспевающим. Те времена были Золотым временем города. Около 350 лет до нашей эры бухарская история и развитие города пропустили на другом уровне из-за племен, которые пришли из Монголии.</p>
<div class=\"photos_line left_margin\"><img title=\"History of Bukhara: stretched back in centuries\" src=\"images/mega/bukhara-history/bukhara-history_1.jpg\" alt=\"History of Bukhara: stretched back in centuries\" width=\"550\" height=\"281\" border=\"0\" /></div>
<p>Перед тем, как Ислам стал главной религией в Бухаре, были две религии, Зороостризм и Несторианство. Но с завоеванием арабами, не сразу, но постепенно в течение многих лет (после того, как произошло кровавое и очень истощающее легендарное сражение Таласа) Ислам стал доминирующей религией.</p>
<h2>Период правления Саманидов в Бухаре. </h2>
<p>В 850 году нашей эры произошло еще одно очень важное событие в бухарской истории, город снова стал столицей другой Империи - Империя Саманидов. Персидский язык снова стал главным языком в городе. Будучи столицей Империи Саманидов, город Бухара процветал и стал интеллектуальным центром мира Мусульман. В этом славном городе появился на свет знаменитый Мухаммед Аль-Бухари, автор хадисов, в которых были описаны подлинные разговоры относительно Пророка Мухаммеда. В истории Бухары произошли еще изменения в 999 году, когда Династию Саманидовсменила Династия Караханидов. Позднее в 13-м веке, было еще одно изменение в правлении, в это время Мухаммед Хорезмшах вторгся город и установил свое правление.</p>
<p>Затем, после Караханидов и периода правления Хорезмшаха, случилось еще одно крупное изменение в правлении Бухары, город завоевали войска Чингиз хана. Онприказал, чтобы сожгли почти половину города, но после того, как люди Бухары согласились подчиниться, он был милосерднее, и город не сжег. МонголыуправлялигородомдовременВеликого Тамерлана (Амир Тимура).</p>
<p>Затем, во времена Шайбанидов, Бухара стала феодальным государством, названым Ханством Бухара. Ханством Бухары управляло несколько правителей, а в 1785 году с помощью Мурад шаха Династия Мангхит, превратило государство в Эмират Бухары.</p>
<div class=\"photos_line left_margin\"><img title=\"History of Bukhara\" src=\"images/mega/bukhara-history/bukhara-history_2.jpg\" alt=\"History of Bukhara\" width=\"550\" height=\"354\" border=\"0\" /></div>
<p>Хорошо известно, что в истории Бухары и Британских и Русских Империях, Эмират Бухары играл очень важную роль. Позднее, в 19-ом столетии, было время проектирования, а затем и строительства длинной железной дороги от каспийского моря.</p>
<p>В течение 1920-1925 гг. в бухарской истории было время Бухарской Народной Советской Республики, которая вошла в состав СССР. </p>
<h2>Современная история Бухары</h2>
<p>В наши дни богатая история бухарского города все еще продолжается, когда Бухара стала частью независимого Узбекистана. Город изменил не многое, улицы и здания те же. И, чтобы почувствовать атмосферу тех событий, описанных выше, все, что вам нужно, так это, посетить Бухару и посмотреть на все его улицы и архитектуру Вашими собственными глазами. </p>
<p>Бухара, так называемый Священный город, очень интересное место, где история может проглядываться очень ясно. Этот город был центром многих Империй, даже центром одной Большой Религии, и это было уничтожено, а затем создалосьиз праха снова, и все еще стоит под теплым солнцем Узбекистана.</p>
<div class=\"photos_line left_margin\"><img title=\"Bukhara history\" src=\"images/mega/bukhara-history/bukhara-history_3.jpg\" alt=\"Bukhara history\" width=\"550\" height=\"378\" border=\"0\" /></div>
</div>[[$SmartargetWhatsappContactUs]]', 2, 'App\Models\City'),
('de', 'value_json', NULL, '<div class=\"mega_topic\">
<h1>Geschichte von Taschkent</h1>
<h3>Geschichte von Taschkent: zurück in die Vergangenheit</h3>
<p>Das 2. Jahrhundert v. Chr. war das erste Mal, als Taschkent in den Quellen von verschiedenen Nationen erwähnt wurde. Diese Erde wurde verschieden genannt: Yuni von Chinesen und Schah von Araber, Chach von Perser. Es ist bekannt, dass der gegenwärtige Name der Stadt Taschkent von der Quelle von Turkic erstens erwähnt wurde.</p>
<p>Taschkent war auch sehr wichtige Stadt unterwegs die Seidenstraße, und es wurde viel Aufmerksamkeit von den Händlern und Reisenden wegen seines warmen Sonnenklimas, glücklicher vorteilhafter Position und Schönheit geschenkt.</p>
<div class=\"photos_line left_margin\"><img title=\"Geschichte von Taschkent: zurück in die Vergangenheit\" src=\"http://www.people-travels.com/images/mega/tashkent-history/tashkent-history_1.jpg\" alt=\"Geschichte von Taschkent: zurück in die Vergangenheit\" width=\"550\" height=\"302\" border=\"0\" /></div>
<p>Taschkent hat wirklich reiche Geschichte: es gab viele wichtige Ansiedlungen auf seinem Territorium, die Stadt wurde mehrere Male (Binkent im 11. Jahrhundert, Shakhruhia in der Zeit der Regierung von Tamerlane) umbenannt.</p>
<p>Taschkent war der Teil von vielen Staaten: Ghengis Khan hat es, Sheibani Khan überwunden; es war auch der Teil von Khanate von Buchara. Das Ende des 19. Jahrhunderts wurde für Taschkent als die Zeit bedeutungsvolle Straßenkreuzung des Handels gekennzeichnet.</p>
<div class=\"photos_line left_margin\"><img title=\"Geschichte von Taschkent\" src=\"http://www.people-travels.com/images/mega/tashkent-history/tashkent-history_2.jpg\" alt=\"Geschichte von Taschkent\" width=\"550\" height=\"293\" border=\"0\" /></div>
<p>Taschkent hat sich sehr verschieden von Buchara oder Samarkand geändert. Diese Stadt war immer im Herzen der Änderungen.Aber noch ist dieser Ort aus dem historischen Gesichtspunkt sehr wichtig.</p>
</div>[[$SmartargetWhatsappContactUs]]', 3, 'App\Models\City'),
('es', 'value_json', NULL, '<div class=\"mega_topic\">
<h1>Historia de Tashkent</h1>
<h3>Historia de Tashkent: un salto atrás en el tiempo</h3>
<p>Por primera vez Tashkent fue mencionado en las origenes diferentes naciones en siglo II AC. Esta tierra se llamaba de otra manera: Yuni por los chinos y Shah por los árabes, Chach por los persas. Esta conocido que el nombre actual de la ciudad de Tashkent se mencionó por primera vez en la origen de Turkos.</p>
<p>Tashkent fue también la ciudad muy importante en el camino de la Ruta de Seda, y se prestó mucha atención por parte de los comerciantes y los viajeros por su clima cálido y soleado, ubicación ventajosa suerte y belleza.</p>
<div class=\"photos_line left_margin\"><img title=\"History of Tashkent: back in time\" src=\"http://www.people-travels.com/images/mega/tashkent-history/tashkent-history_1.jpg\" alt=\"History of Tashkent: back in time\" width=\"550\" height=\"302\" border=\"0\" /></div>
<p>Tashkent tiene la historia realmente rica: había muchos asentamientos importantes en su territorio, la ciudad se cambió su nombre unos veces (Binkent en el siglo XI, Shakhruhia en la época del gobiernamiento de Tamerlán).</p>
<p>Era la parte de muchos estados: Gengis Khan y Sheibani Khan lo conquistaron; también fue parte del Janato de Bukhara. Al final del siglo XIX se caracterizó por Tashkent como el momento de convertirse una vez más a un significativo cruce de caminos del comercio.</p>
<div class=\"photos_line left_margin\"><img title=\"Historia de Tashkent\" src=\"http://www.people-travels.com/images/mega/tashkent-history/tashkent-history_2.jpg\" alt=\"Historia de Tashkent\" width=\"550\" height=\"293\" border=\"0\" /></div>
<p>Tashkent se cambio mucho como Bukhara o Samarcanda. Esta ciudad siempre estuvo en el corazón de cambios, siguiendo el viento de los cambios y al estar más bella y más moderno de cada año de existencia. Pero todavia este lugar es muy importante desde el punto de vista histórico.</p>
</div>[[$SmartargetWhatsappContactUs]]', 3, 'App\Models\City');