UPDATE sights SET preview_image = 'images/sights/bibi-khanum-madrasah.jpg' WHERE id = 1;
UPDATE sights SET preview_image = 'images/sights/ulugbek-observatory.jpg' WHERE id = 2;
UPDATE sights SET preview_image = 'images/sights/khodja-akhrar-ensemble.jpg' WHERE id = 3;
UPDATE sights SET preview_image = 'images/sights/afrasiab-the-settlement-of-the-ancient-orient.jpg' WHERE id = 4;
UPDATE sights SET preview_image = 'images/events/urgut1.jpg' WHERE id = 5;
UPDATE sights SET preview_image = 'images/mega/sightseeing-in-samarkand/registan.jpg' WHERE id = 6;
UPDATE sights SET preview_image = 'images/sights/shakhi-zinda-necropolis.jpg' WHERE id = 7;
UPDATE sights SET preview_image = 'images/sights/sher-dor-madrassah.jpg' WHERE id = 8;
UPDATE sights SET preview_image = 'images/sights/tilla-kori-madrasah.jpg' WHERE id = 9;
UPDATE sights SET preview_image = 'images/sights/prophet-daniiels-mausoleum.jpg' WHERE id = 10;
UPDATE sights SET preview_image = 'images/sights/gur-emir-mausoleum.jpg' WHERE id = 11;
UPDATE sights SET preview_image = 'images/sights/rukhabad-mausoleum.jpg' WHERE id = 12;
UPDATE sights SET preview_image = 'images/paper-mill-in-samarkand.jpg' WHERE id = 13;
UPDATE sights SET preview_image = 'images/sights/ulugbek-madrasah.jpg' WHERE id = 14;
UPDATE sights SET preview_image = 'images/sights/hudzhum-carpet-factory-of-samarkand.jpg' WHERE id = 15;
UPDATE sights SET preview_image = 'images/sights/siab-bazaar.jpg' WHERE id = 16;
UPDATE sights SET preview_image = 'images/sights/mosque-hazrat-hyzr.jpg' WHERE id = 17;
UPDATE sights SET preview_image = 'images/sights/khoja-abdi-darun-aini-ensemble-in-samarkand.jpg' WHERE id = 18;
UPDATE sights SET preview_image = 'images/sights/mausoleum-of-imam-al-maturidi.jpg' WHERE id = 19;
UPDATE sights SET preview_image = 'images/sights/national-dances-of-samarkand.jpg' WHERE id = 20;
UPDATE sights SET preview_image = 'images/sights/the-roman-catholic-church-in-samarkand.jpg' WHERE id = 21;
UPDATE sights SET preview_image = 'images/sights/the-history-of-the-mausoleum-of-imam-al-bukhari.jpg' WHERE id = 22;
UPDATE sights SET preview_image = 'images/sights/afrasiab-museum.jpg' WHERE id = 23;
UPDATE sights SET preview_image = 'images/sights/cave-of-hazrat-daud.jpg' WHERE id = 24;
UPDATE sights SET preview_image = 'images/sights/mausoleum-of-ishratkhan-prehistory-construction-decor-and-planning-of-the-mausoleum.jpg' WHERE id = 25;
UPDATE sights SET preview_image = 'images/sights/the-memorial-museum-of-mirzo-ulugbek-is-situated-near-ulugbek-observatory.jpg' WHERE id = 26;
UPDATE sights SET preview_image = 'images/sights/international-museum-of-peace-and-solidarity.jpg' WHERE id = 27;
UPDATE sights SET preview_image = 'images/sights/samarkand-winery-history.jpg' WHERE id = 28;
UPDATE sights SET preview_image = 'images/Samarkand sights/Urgut-Chor-Chinor-Garden.jpg' WHERE id = 29;
UPDATE sights SET preview_image = 'images/Samarkand sights/Amankutan.jpg' WHERE id = 30;
UPDATE sights SET preview_image = 'images/Samarkand sights/Kusam-ibn-Abbas-mausoleum-in-Samarkand.jpg' WHERE id = 31;
UPDATE sights SET preview_image = 'images/Samarkand sights/Chorsu-Art-Gallery-in-Samarkand.jpg' WHERE id = 32;
UPDATE sights SET preview_image = 'images/Samarkand sights/Samarkand-railway-station.jpg' WHERE id = 33;
UPDATE sights SET preview_image = 'images/Samarkand sights/State-Museum-of-Culture-History-of-Uzbekistan.jpg' WHERE id = 34;
UPDATE sights SET preview_image = 'images/sights/karakul-reserve.jpg' WHERE id = 35;
UPDATE sights SET preview_image = 'images/sights/mausoleum-of-the-samanids.jpg' WHERE id = 36;
UPDATE sights SET preview_image = 'images/sights/dzheiran-reserve.jpg' WHERE id = 37;
UPDATE sights SET preview_image = 'images/sights/caravanserai-nougat.jpg' WHERE id = 38;
UPDATE sights SET preview_image = 'images/mega/bukhara-sightseeing/lyabi-hauz-ensemble.jpg' WHERE id = 39;
UPDATE sights SET preview_image = 'images/sights/bakhauddin-nakshbandi-mausoleum.jpg' WHERE id = 40;
UPDATE sights SET preview_image = 'images/sights/vabkent-minaret.jpg' WHERE id = 41;
UPDATE sights SET preview_image = 'images/sights/ulugbek-madrasah-in-bukhara.jpg' WHERE id = 42;
UPDATE sights SET preview_image = 'images/sights/Khodja-Zaynutdin-Complex.jpg' WHERE id = 43;
UPDATE sights SET preview_image = 'images/events/gijduvan2.jpg' WHERE id = 44;
UPDATE sights SET preview_image = 'images/events/varaksha1.jpg' WHERE id = 45;
UPDATE sights SET preview_image = 'images/events/vardanzi1.jpg' WHERE id = 46;
UPDATE sights SET preview_image = 'images/events/paikend1.jpg' WHERE id = 47;
UPDATE sights SET preview_image = 'images/events/shafirkan.jpg' WHERE id = 48;
UPDATE sights SET preview_image = 'images/sights/kalyan-minaret.jpg' WHERE id = 49;
UPDATE sights SET preview_image = 'images/events/sitorai.jpg' WHERE id = 50;
UPDATE sights SET preview_image = 'images/events/talipach-gate.jpg' WHERE id = 51;
UPDATE sights SET preview_image = 'images/events/bolo-hauz.jpg' WHERE id = 52;
UPDATE sights SET preview_image = 'images/events/din-bokharzi.jpg' WHERE id = 53;
UPDATE sights SET preview_image = 'images/sights/nadir-divanbegi-madrasah.jpg' WHERE id = 54;
UPDATE sights SET preview_image = 'images/sights/visit-the-madrassa-mir-arab.jpg' WHERE id = 55;
UPDATE sights SET preview_image = 'images/sights/the-ancient-ark-fortress.jpg' WHERE id = 56;
UPDATE sights SET preview_image = 'images/sights/chor-minor-madrasah.jpg' WHERE id = 57;
UPDATE sights SET preview_image = 'images/sights/emir-alim-khan-madrasah.jpg' WHERE id = 58;
UPDATE sights SET preview_image = 'images/sights/abdulaziz-madrasah.jpg' WHERE id = 59;
UPDATE sights SET preview_image = 'images/sights/khalif-hudoydod-complex.jpg' WHERE id = 60;
UPDATE sights SET preview_image = 'images/sights/magoki-attari-mosque.jpg' WHERE id = 61;
UPDATE sights SET preview_image = 'images/sights/chashma-ayub.jpg' WHERE id = 62;
UPDATE sights SET preview_image = 'images/sights/abdalhalik-al-gijduvani-complex.jpg' WHERE id = 63;
UPDATE sights SET preview_image = 'images/sights/zindan-of-emir.jpg' WHERE id = 64;
UPDATE sights SET preview_image = 'images/sights/sayyid-amir-kula-tomb-in-bukhara.jpg' WHERE id = 65;
UPDATE sights SET preview_image = 'images/sights/kurpa-mosque-in-bukhara.jpg' WHERE id = 66;
UPDATE sights SET preview_image = 'images/sights/central-bazaar-in-bukhara.jpg' WHERE id = 67;
UPDATE sights SET preview_image = 'images/sights/buyan-kuli-khan-mausoleum-in-bukhara.jpg' WHERE id = 68;
UPDATE sights SET preview_image = 'images/sights/ustrushana.jpg' WHERE id = 69;
UPDATE sights SET preview_image = 'images/sights/burial-of-sheih-akhbor-vali-in-bukhara-region.jpg' WHERE id = 70;
UPDATE sights SET preview_image = 'images/sights/thumbnail-art-of-bukhara.jpg' WHERE id = 71;
UPDATE sights SET preview_image = 'images/sights/bukhara-carpets.jpg' WHERE id = 72;
UPDATE sights SET preview_image = 'images/sights/intangible-heritage-of-bukhara.jpg' WHERE id = 73;
UPDATE sights SET preview_image = 'images/sights/kukeldash-madrasah-in-bukhara.jpg' WHERE id = 74;
UPDATE sights SET preview_image = 'images/sights/history-of-chor-bakr-necropolis.jpg' WHERE id = 75;
UPDATE sights SET preview_image = 'images/sights/kosh-madrasah-ensemble-madrasah-of-modari-khan-and-madrasah-of-abdullah-khan.jpg' WHERE id = 76;
UPDATE sights SET preview_image = 'images/sights/khoja-gaukushon-ensemble-history.jpg' WHERE id = 77;
UPDATE sights SET preview_image = 'images/sights/djami-mosque-in-bukhara.jpg' WHERE id = 78;
UPDATE sights SET preview_image = 'images/sights/kalyan-mosque-in-bukhara.jpg' WHERE id = 79;
UPDATE sights SET preview_image = 'images/sights/fayzulla-khodjaev-museum-in-bukhara.jpg' WHERE id = 80;
UPDATE sights SET preview_image = 'images/sights/mosque-fayzabad-khanqah-in-bukhara.jpg' WHERE id = 81;
UPDATE sights SET preview_image = 'images/sights/poy-kalyan-ensemble.jpg' WHERE id = 82;
UPDATE sights SET preview_image = 'images/sights/mausoleum-of-imam-abu-khafs-kabir-in-bukhara.jpg' WHERE id = 83;
UPDATE sights SET preview_image = 'images/sights/bukhara-state-museum.jpg' WHERE id = 84;
UPDATE sights SET preview_image = 'images/sights/two-remained-baths-khammam-in-bukhara.jpg' WHERE id = 85;
UPDATE sights SET preview_image = 'images/Bukhara sights/Isteza-Madrasah-in-Bukhara.jpg' WHERE id = 86;
UPDATE sights SET preview_image = 'images/Bukhara sights/Registan-square-Bukhara.jpg' WHERE id = 87;
UPDATE sights SET preview_image = 'images/Bukhara sights/Bukhara-gold-embroidery-factory.jpg' WHERE id = 88;
UPDATE sights SET preview_image = 'images/Bukhara sights/monument-to-Khoja-Nasreddin-in-Bukhara.jpg' WHERE id = 89;
UPDATE sights SET preview_image = 'images/Bukhara sights/complex-Kiz-bibi-in-Bukhara.jpg' WHERE id = 90;
UPDATE sights SET preview_image = 'images/Bukhara sights/water-tower-Shukhov-Bukhara.jpg' WHERE id = 91;
UPDATE sights SET preview_image = 'images/Bukhara sights/Bukhara-sinagogue.jpg' WHERE id = 92;
UPDATE sights SET preview_image = 'images/Bukhara sights/Abu-Ali-ibn-Sino-memorial-museum.jpg' WHERE id = 93;
UPDATE sights SET preview_image = 'images/Bukhara sights/Mullo-Tursunjon-Madrasah-Bukhara.jpg' WHERE id = 94;
UPDATE sights SET preview_image = 'images/Bukhara sights/Goziyon-madrasah-in-Bukhara.jpg' WHERE id = 95;
UPDATE sights SET preview_image = 'images/Bukhara sights/trade-domes-in-Bukhara.jpg' WHERE id = 96;
UPDATE sights SET preview_image = 'images/Bukhara sights/Kuleta-caravanserai-Bukhara.jpg' WHERE id = 97;
UPDATE sights SET preview_image = 'images/Bukhara sights/Balyand-mosque-Bukhara.JPG' WHERE id = 98;
UPDATE sights SET preview_image = 'images/sights/bolshoi-opera-and-ballet-theatre-in-tashkent.jpg' WHERE id = 99;
UPDATE sights SET preview_image = 'images/sights/monument-of-amir-temur-in-tashkent.jpg' WHERE id = 100;
UPDATE sights SET preview_image = 'images/sights/tashkent-botanical-garden.jpg' WHERE id = 101;
UPDATE sights SET preview_image = 'images/sights/alay-bazaar.jpg' WHERE id = 102;
UPDATE sights SET preview_image = 'images/japanese-garden-in-tashkent_.jpg' WHERE id = 103;
UPDATE sights SET preview_image = 'images/events/shohruhiya.jpg' WHERE id = 104;
UPDATE sights SET preview_image = 'images/sights/suzukh-ata-mausoleum.jpg' WHERE id = 105;
UPDATE sights SET preview_image = 'images/sights/mausoleum-of-yunus-khan.jpg' WHERE id = 106;
UPDATE sights SET preview_image = 'images/sights/the-charm-of-sheikhantaur-ensemble.jpg' WHERE id = 107;
UPDATE sights SET preview_image = 'images/sights/legend-about-muyiy-mubarak-madrasah.jpg' WHERE id = 108;
UPDATE sights SET preview_image = 'images/mega/tashkent-sightseeing/kukeldash-madrassah.jpg' WHERE id = 109;
UPDATE sights SET preview_image = 'images/sights/kaffal-ash-shash-mausoleum.jpg' WHERE id = 110;
UPDATE sights SET preview_image = 'images/mega/tashkent-sightseeing/old-towns-chorsu-bazaar.jpg' WHERE id = 111;
UPDATE sights SET preview_image = 'images/museums/museum-of-esenin .jpg' WHERE id = 112;
UPDATE sights SET preview_image = 'images/museums/Ashrafi-house-museum.jpg' WHERE id = 113;
UPDATE sights SET preview_image = 'images/sights/independence-square.jpg' WHERE id = 114;
UPDATE sights SET preview_image = 'images/sights/polish-catholic-church-in-tashkent.jpg' WHERE id = 115;
UPDATE sights SET preview_image = 'images/sights/yangiabad-bazaar-in-tashkent.jpg' WHERE id = 116;
UPDATE sights SET preview_image = 'images/sights/Kukeldash-Madrassa-in-Tashkent.jpg' WHERE id = 117;
UPDATE sights SET preview_image = 'images/sights/Monument-Courage.jpg' WHERE id = 118;
UPDATE sights SET preview_image = 'images/sights/Park-Bobur.jpg' WHERE id = 119;
UPDATE sights SET preview_image = 'images/sights/chimes--in-tashkent.jpg' WHERE id = 120;
UPDATE sights SET preview_image = 'images/sights/tashkent-zoo.jpg' WHERE id = 121;
UPDATE sights SET preview_image = 'images/sights/khamid-alimdjan-monument.jpg' WHERE id = 122;
UPDATE sights SET preview_image = 'images/events/gazalkent1.jpg' WHERE id = 123;
UPDATE sights SET preview_image = 'images/events/сhirchik1.jpg' WHERE id = 124;
UPDATE sights SET preview_image = 'images/beldersay-in-uzbekistan.jpg' WHERE id = 125;
UPDATE sights SET preview_image = 'images/events/khumsan1.jpg' WHERE id = 126;
UPDATE sights SET preview_image = 'images/events/minguruk3.jpg' WHERE id = 127;
UPDATE sights SET preview_image = 'images/events/zarautsay2.jpg' WHERE id = 128;
UPDATE sights SET preview_image = 'images/events/hodjikent1.jpg' WHERE id = 129;
UPDATE sights SET preview_image = 'images/events/shoshtepa.jpg' WHERE id = 130;
UPDATE sights SET preview_image = 'images/events/brichmulla.jpg' WHERE id = 131;
UPDATE sights SET preview_image = 'images/events/chatkal1.jpg' WHERE id = 132;
UPDATE sights SET preview_image = 'images/events/khodjikent1.jpg' WHERE id = 133;
UPDATE sights SET preview_image = 'images/events/nanay.jpg' WHERE id = 134;
UPDATE sights SET preview_image = 'images/events/aktash.jpg' WHERE id = 135;
UPDATE sights SET preview_image = 'images/events/kanka.jpg' WHERE id = 136;
UPDATE sights SET preview_image = 'images/events/hast-imam.jpg' WHERE id = 137;
UPDATE sights SET preview_image = 'images/memorial-complex-zangi-ota-in-tashkent-region.jpg' WHERE id = 138;
UPDATE sights SET preview_image = 'images/events/sheikhantaur.jpg' WHERE id = 139;
UPDATE sights SET preview_image = 'images/sights/sorrowful-mother.jpg' WHERE id = 140;
UPDATE sights SET preview_image = 'images/sights/barak-khan-madrasah-the-sacred-item-of-history.jpg' WHERE id = 141;
UPDATE sights SET preview_image = 'images/sights/juma-mosque-of-hodja-akhrar.jpg' WHERE id = 142;
UPDATE sights SET preview_image = 'images/museums/Yunus-Rajabi-museum.jpg' WHERE id = 143;
UPDATE sights SET preview_image = 'images/Tashkent parks/Ankhor.jpg' WHERE id = 144;
UPDATE sights SET preview_image = 'images/chimgan-mountains-history.jpg' WHERE id = 145;
UPDATE sights SET preview_image = 'images/sights/parpi-ota-in-almalyk.jpg' WHERE id = 146;
UPDATE sights SET preview_image = 'images/sights/subway-of-tashkent.jpg' WHERE id = 147;
UPDATE sights SET preview_image = 'images/sights/visit-sardoba-kaynargumbaz.jpg' WHERE id = 148;
UPDATE sights SET preview_image = 'images/sights/center-of-culture-of-ikuo-hirayama-in-tashkent.jpg' WHERE id = 149;
UPDATE sights SET preview_image = 'images/museums/polytechnic-museum-in-Tashkent.jpg' WHERE id = 150;
UPDATE sights SET preview_image = 'images/sights/romanov-palace-in-tashkent.jpg' WHERE id = 151;
UPDATE sights SET preview_image = 'images/sights/amir-timur-museum-in-tashkent.jpg' WHERE id = 152;
UPDATE sights SET preview_image = 'images/sights/amir-timur-square-history.jpg' WHERE id = 153;
UPDATE sights SET preview_image = 'images/sights/tv-tower-in-tashkent.jpg' WHERE id = 154;
UPDATE sights SET preview_image = 'images/sights/state-museum-of-history-of-uzbekistan.jpg' WHERE id = 155;
UPDATE sights SET preview_image = 'images/sights/history-of-the-state-museum-of-applied-art.jpg' WHERE id = 156;
UPDATE sights SET preview_image = 'images/sights/ural-tansykbaev-memorial-museum-in-tashkent.jpg' WHERE id = 157;
UPDATE sights SET preview_image = 'images/sights/minor-mosque-in-tashkent.jpg' WHERE id = 158;
UPDATE sights SET preview_image = 'images/sights/orthodox-churches-in-uzbekistan.jpg' WHERE id = 159;
UPDATE sights SET preview_image = 'images/sights/tashkent-museum-of-railway-technics.jpg' WHERE id = 160;
UPDATE sights SET preview_image = 'images/sights/memorial-house-museum-of-tamara-khanum.jpg' WHERE id = 161;
UPDATE sights SET preview_image = 'images/sights/tashkent-imam-al-bukhari-islamic-institute.jpg' WHERE id = 162;
UPDATE sights SET preview_image = 'images/sights/tillya-sheikh-mosque-in-tashkent.jpg' WHERE id = 163;
UPDATE sights SET preview_image = 'images/sights/tashkent-airport.jpg' WHERE id = 164;
UPDATE sights SET preview_image = 'images/sights/chapel-near-the-kamolon-gates-of-tashkent.jpg' WHERE id = 165;
UPDATE sights SET preview_image = 'images/sights/anbar-bibi-mausoleum-in-tashkent.jpg' WHERE id = 166;
UPDATE sights SET preview_image = 'images/sights/german-kirche-in-tashkent.jpg' WHERE id = 167;
UPDATE sights SET preview_image = 'images/sights/art-gallery-nbu-in-tashkent.jpg' WHERE id = 168;
UPDATE sights SET preview_image = 'images/sights/mausoleum-of-sheykh-zayniddin-bobo.jpg' WHERE id = 169;
UPDATE sights SET preview_image = 'images/sights/museum-of-victims-of-political-repression.jpg' WHERE id = 170;
UPDATE sights SET preview_image = 'images/sights/central-exhibition-hall-of-the-academy-of-arts-in-tashkent.jpg' WHERE id = 171;
UPDATE sights SET preview_image = 'images/sights/state-art-museum-of-uzbekistan.jpg' WHERE id = 172;
UPDATE sights SET preview_image = 'images/sights/centre-of-national-arts-history.jpg' WHERE id = 173;
UPDATE sights SET preview_image = 'images/sights/museum-of-geology-in-tashkent.jpg' WHERE id = 174;
UPDATE sights SET preview_image = 'images/sights/charvak-reservoir.jpg' WHERE id = 175;
UPDATE sights SET preview_image = 'images/sights/abul-kasim-madrasah.jpg' WHERE id = 176;
UPDATE sights SET preview_image = 'images/sights/the-state-academic-theatre-of-opera-and-ballet-named-after-alisher-navoi.jpg' WHERE id = 177;
UPDATE sights SET preview_image = 'images/sights/karakiyasay-petroglyphs.jpg' WHERE id = 178;
UPDATE sights SET preview_image = 'images/Tashkent sights/Tashkent-golf-club.png' WHERE id = 179;
UPDATE sights SET preview_image = 'images/Tashkent sights/Uzbekistan-National-library-named-after-Alisher-Navoi.jpg' WHERE id = 180;
UPDATE sights SET preview_image = 'images/Tashkent sights/Kaplan\'s-pharmacy.jpg' WHERE id = 181;
UPDATE sights SET preview_image = 'images/Tashkent sights/Solar-Institute-in-Parkent.jpg' WHERE id = 182;
UPDATE sights SET preview_image = 'images/Tashkent sights/International-Caravanserai-of-Culture-named-after-Ikuo-Hirayama-in-Tashkent.jpg' WHERE id = 183;
UPDATE sights SET preview_image = 'images/Tashkent sights/Shastri-Monument-in-Tashkent.jpg' WHERE id = 184;
UPDATE sights SET preview_image = 'images/uzbekistan-rivers/Bozsu-canal-in-Tashkent.jpg' WHERE id = 185;
UPDATE sights SET preview_image = 'images/uzbekistan-rivers/Salar-canal.jpg' WHERE id = 186;
UPDATE sights SET preview_image = 'images/Theatres/Tashkent-circus.jpg' WHERE id = 187;
UPDATE sights SET preview_image = 'images/museums/State-Museum-of-Nature-of-Uzbekistan.jpg' WHERE id = 188;
UPDATE sights SET preview_image = 'images/Theatres/Aladdin-Theater.jpg' WHERE id = 189;
UPDATE sights SET preview_image = 'images/museums/Museum-of-Astronomy-in-Tashkent.jpg' WHERE id = 190;
UPDATE sights SET preview_image = 'images/Theatres/Mukimi-theatre.jpg' WHERE id = 191;
UPDATE sights SET preview_image = 'images/Tashkent sights/Broadway-in-Tashkent-city.jpg' WHERE id = 192;
UPDATE sights SET preview_image = 'images/sights/shirgazikhan-madrasah-in-khiva.jpg' WHERE id = 193;
UPDATE sights SET preview_image = 'images/sights/kazi-kalyan-madrasah.jpg' WHERE id = 194;
UPDATE sights SET preview_image = 'images/sights/atadjan-complex.jpg' WHERE id = 195;
UPDATE sights SET preview_image = 'images/sights/sha-qalandar-bobo-complex.jpg' WHERE id = 196;
UPDATE sights SET preview_image = 'images/sights/chadra-hawlyi-palace.jpg' WHERE id = 197;
UPDATE sights SET preview_image = 'images/sights/madrassah-and-minaret-sayyid-niaz-shalykarbay.jpg' WHERE id = 198;
UPDATE sights SET preview_image = 'images/sights/abd-al-bobo-complex.jpg' WHERE id = 199;
UPDATE sights SET preview_image = 'images/mega/sightseeing-in-khiva/the-mausoleum-of-sheikh-syed-alauddin.jpg' WHERE id = 200;
UPDATE sights SET preview_image = 'images/mega/sightseeing-in-khiva/citadel-kunya-ark.jpg' WHERE id = 201;
UPDATE sights SET preview_image = 'images/mega/sightseeing-in-khiva/the-fortress-ickhan-kala.jpg' WHERE id = 202;
UPDATE sights SET preview_image = 'images/sights/djuma-mosque.jpg' WHERE id = 203;
UPDATE sights SET preview_image = 'images/sights/Monument-of-Avesta.jpg' WHERE id = 204;
UPDATE sights SET preview_image = 'images/sights/Nurullabay-Palace.jpg' WHERE id = 205;
UPDATE sights SET preview_image = 'images/sights/makhdoom-talib-madrasah.jpg' WHERE id = 206;
UPDATE sights SET preview_image = 'images/sights/bikanzhan-bica-complex.jpg' WHERE id = 207;
UPDATE sights SET preview_image = 'images/sights/kutlug-murad-complex.jpg' WHERE id = 208;
UPDATE sights SET preview_image = 'images/sights/alla-kuli-khan-caravanserai.jpg' WHERE id = 209;
UPDATE sights SET preview_image = 'images/events/toprak-kala-2.jpg' WHERE id = 210;
UPDATE sights SET preview_image = 'images/sights/visit-islom-khodja-minaret.jpg' WHERE id = 211;
UPDATE sights SET preview_image = 'images/sights/muhammad-amin-madrasah.jpg' WHERE id = 212;
UPDATE sights SET preview_image = 'images/sights/pahlavan-mahmud-madrasah-and-minaret.jpg' WHERE id = 213;
UPDATE sights SET preview_image = 'images/sights/mazari-sharif-madrasah.jpg' WHERE id = 214;
UPDATE sights SET preview_image = 'images/sights/ak-mosque.jpg' WHERE id = 215;
UPDATE sights SET preview_image = 'images/sights/visit-kalta-minar-minaret.jpg' WHERE id = 216;
UPDATE sights SET preview_image = 'images/sights/visit-palace-tash-hawley.jpg' WHERE id = 217;
UPDATE sights SET preview_image = 'images/sights/arab-muhammad-khan-madrasah.jpg' WHERE id = 218;
UPDATE sights SET preview_image = 'images/sights/said-muhammad-khan-madrasah.jpg' WHERE id = 219;
UPDATE sights SET preview_image = 'images/sights/mukhammad-rahim-khan-madrasah.jpg' WHERE id = 220;
UPDATE sights SET preview_image = 'images/sights/matpanabay-madrasah-in-khiva.jpg' WHERE id = 221;
UPDATE sights SET preview_image = 'images/sights/bagbanly-mosque-in-khiva.jpg' WHERE id = 222;
UPDATE sights SET preview_image = 'images/sights/yusuf-yasulbashi-madrasah-in-khiva.jpg' WHERE id = 223;
UPDATE sights SET preview_image = 'images/sights/payando-mausoleum.jpg' WHERE id = 224;
UPDATE sights SET preview_image = 'images/sights/matniyaz-divanbegi-madrasah-in-khiva.jpg' WHERE id = 225;
UPDATE sights SET preview_image = 'images/sights/hassan-murat-kushbegi-mosque-in-khiva.jpg' WHERE id = 226;
UPDATE sights SET preview_image = 'images/sights/dishan-kala-in-khiva.jpg' WHERE id = 227;
UPDATE sights SET preview_image = 'images/sights/yar-muhammad-devon-mosque-in-khiva.jpg' WHERE id = 228;
UPDATE sights SET preview_image = 'images/sights/bazaar-of-old-khiva.jpg' WHERE id = 229;
UPDATE sights SET preview_image = 'images/sights/palvan-kari-complex-in-khiva.jpg' WHERE id = 230;
UPDATE sights SET preview_image = 'images/sights/shahimardan-mausoleum-in-khiva.jpg' WHERE id = 231;
UPDATE sights SET preview_image = 'images/sights/sheikh-mukhtar-ata-mosque-in-khiva.jpg' WHERE id = 232;
UPDATE sights SET preview_image = 'images/sights/mamad-maram-madrasah-in-khiva.jpg' WHERE id = 233;
UPDATE sights SET preview_image = 'images/sights/tort-shaffaz-madrasah-in-khiva.jpg' WHERE id = 234;
UPDATE sights SET preview_image = 'images/sights/rafanek-madrasah-in-khiva.jpg' WHERE id = 235;
UPDATE sights SET preview_image = 'images/sights/uch-avlioli-mavsoleum-in-khiva.jpg' WHERE id = 236;
UPDATE sights SET preview_image = 'images/sights/visit-bibi-hajar-mausoleum.jpg' WHERE id = 237;
UPDATE sights SET preview_image = 'images/sights/sayid-bai-minaret-in-khiva.jpg' WHERE id = 238;
UPDATE sights SET preview_image = 'images/sights/zoroastrian-heritage-of-khoresm.jpg' WHERE id = 239;
UPDATE sights SET preview_image = 'images/sights/airtam-complex-in-khoresm.jpg' WHERE id = 240;
UPDATE sights SET preview_image = 'images/sights/said-mauhhammad-mahiriy-in-khiva.jpg' WHERE id = 241;
UPDATE sights SET preview_image = 'images/sights/palvan-darwaza-bazaar-of-khiva.jpg' WHERE id = 242;
UPDATE sights SET preview_image = 'images/sights/qibla-tosabog-in-khiva.jpg' WHERE id = 243;
UPDATE sights SET preview_image = 'images/sights/intangible-heritage-of-khiva.jpg' WHERE id = 244;
UPDATE sights SET preview_image = 'images/sights/unique-architectural-epigraphy-of-khiva.jpg' WHERE id = 245;
UPDATE sights SET preview_image = 'images/sights/jewelcrafting-of-khiva.jpg' WHERE id = 246;
UPDATE sights SET preview_image = 'images/sights/pottery-of-khiva.jpg' WHERE id = 247;
UPDATE sights SET preview_image = 'images/sights/museum-of-the-history-of-khorezm.jpg' WHERE id = 248;
UPDATE sights SET preview_image = 'images/sights/khazarasp-fortress-in-khiva.jpg' WHERE id = 249;
UPDATE sights SET preview_image = 'images/sights/ichan-kala-history.jpg' WHERE id = 250;
UPDATE sights SET preview_image = 'images/sights/allakuli-khan-madrasah-in-khiva.jpg' WHERE id = 251;
UPDATE sights SET preview_image = 'images/sights/khoja-berdibai-madrasah-history.jpg' WHERE id = 252;
UPDATE sights SET preview_image = 'images/sights/islam-khoja-complex-in-khiva.jpg' WHERE id = 253;
UPDATE sights SET preview_image = 'images/Khiva sights/Kurnish-khan-palace-in-Khiva.jpg' WHERE id = 254;
UPDATE sights SET preview_image = 'images/Khiva sights/well-Kheyvak-Khiva.jpg' WHERE id = 255;
UPDATE sights SET preview_image = 'images/Khiva sights/Anush-khan-baths.jpg' WHERE id = 256;
UPDATE sights SET preview_image = 'images/Khiva sights/carpets-of-Khorezm.jpg' WHERE id = 257;
UPDATE sights SET preview_image = 'images/Khiva sights/Puppet Theater in Khiva.jpg' WHERE id = 258;
UPDATE sights SET preview_image = 'images/sights/chashma-complex-in-nurata.jpg' WHERE id = 259;
UPDATE sights SET preview_image = 'images/mega/nurata-sightseeing/aydarkul-lake.jpg' WHERE id = 260;
UPDATE sights SET preview_image = 'images/sights/aidar-yurt-camp-in-nurata.jpg' WHERE id = 261;
UPDATE sights SET preview_image = 'images/sights/namazgokh-mosque-in-nurata.jpg' WHERE id = 262;
UPDATE sights SET preview_image = 'images/sights/natural-sites-in-nuratau-mountains.jpg' WHERE id = 263;
UPDATE sights SET preview_image = 'images/sights/flora-and-fauna-of-nurata-natural-reserve.jpg' WHERE id = 264;
UPDATE sights SET preview_image = 'images/sights/sights-near-sentob-village.jpg' WHERE id = 265;
UPDATE sights SET preview_image = 'images/sights/darus-saodat-complex.jpg' WHERE id = 266;
UPDATE sights SET preview_image = 'images/mega/shahrizabs-sightseeing/mosque-kok-gumbaz.jpg' WHERE id = 267;
UPDATE sights SET preview_image = 'images/mega/shahrizabs-sightseeing/monument-of-tamerlane.jpg' WHERE id = 268;
UPDATE sights SET preview_image = 'images/sights/aksaray-in-shahrisabz.jpg' WHERE id = 269;
UPDATE sights SET preview_image = 'images/events/ak-saray.jpg' WHERE id = 270;
UPDATE sights SET preview_image = 'images/mega/shahrizabs-sightseeing/complex-dorut-tillavat-and-mausoleum-of-shamsiddin-kulol.jpg' WHERE id = 271;
UPDATE sights SET preview_image = 'images/sights/durut-tillavat-complex.jpg' WHERE id = 272;
UPDATE sights SET preview_image = 'images/sights/gumbazy-seidon-tomb-in-shahrisabz.jpg' WHERE id = 273;
UPDATE sights SET preview_image = 'images/sights/crypt-of-amir-timur-in-shakhrisabz.jpg' WHERE id = 274;
UPDATE sights SET preview_image = 'images/sights/visit-shakhrisabz-alley.jpg' WHERE id = 275;
UPDATE sights SET preview_image = 'images/sights/gumbaz-mausoleum.jpg' WHERE id = 278;
UPDATE sights SET preview_image = 'images/sights/visit-kitab-reserve.jpg' WHERE id = 279;
UPDATE sights SET preview_image = 'images/mega/karshi/old-bridge-of-nicholas.jpg' WHERE id = 280;
UPDATE sights SET preview_image = 'images/mega/karshi/sardoba-sight-of-karshi.jpg' WHERE id = 281;
UPDATE sights SET preview_image = 'images/mega/karshi/eternal-flame.jpg' WHERE id = 282;
UPDATE sights SET preview_image = 'images/sights/sufi-monastery-langar-ota.jpg' WHERE id = 283;
UPDATE sights SET preview_image = 'images/sights/majestic-springs-of-kashkadarya.jpg' WHERE id = 284;
UPDATE sights SET preview_image = 'images/sights/petroglyphs-of-siypantosh-in-kashkadarya.jpg' WHERE id = 285;
UPDATE sights SET preview_image = 'images/sights/maidanak-astrophysical-observatory-in-kashkadarya.jpg' WHERE id = 286;
UPDATE sights SET preview_image = 'images/sights/visit-kuruksay.jpg' WHERE id = 287;
UPDATE sights SET preview_image = 'images/sights/qok-goombas-mosque-in-karshi.jpg' WHERE id = 288;
UPDATE sights SET preview_image = 'images/Karshi sights/Erkurgan-settlement-Karshi.jpg' WHERE id = 289;
UPDATE sights SET preview_image = 'images/sights/mausoleum-of-mir-saeed-bahrom.jpg' WHERE id = 290;
UPDATE sights SET preview_image = 'images/events/zarafshan2.jpg' WHERE id = 291;
UPDATE sights SET preview_image = 'images/events/rabat-malik.jpg' WHERE id = 292;
UPDATE sights SET preview_image = 'images/sights/khoja-hisrava-mausoleum-in-navoi.jpg' WHERE id = 293;
UPDATE sights SET preview_image = 'images/sights/kasim-sheikh-khanaka-in-navoi.jpg' WHERE id = 294;
UPDATE sights SET preview_image = 'images/sights/kizilkum-desert-in-uzbekistan.jpg' WHERE id = 295;
UPDATE sights SET preview_image = 'images/sights/zarafshan-reserve.jpg' WHERE id = 296;
UPDATE sights SET preview_image = 'images/sights/burkuttepa-in-navoi.jpg' WHERE id = 297;
UPDATE sights SET preview_image = 'images/sights/nur-fortress-in-navoi.jpg' WHERE id = 298;
UPDATE sights SET preview_image = 'images/sights/chordara-сastle-in-navoi.jpg' WHERE id = 299;
UPDATE sights SET preview_image = 'images/sights/visit-deggaron-mosque.jpg' WHERE id = 300;
UPDATE sights SET preview_image = 'images/sights/chormgar-in-navoi.jpg' WHERE id = 301;
UPDATE sights SET preview_image = 'images/sights/tash-mosque-in-navoi.jpg' WHERE id = 302;
UPDATE sights SET preview_image = 'images/sights/petroglyphs-of-navoi.jpg' WHERE id = 303;
UPDATE sights SET preview_image = 'images/sights/kurgan-mosque-in-navoi.jpg' WHERE id = 304;
UPDATE sights SET preview_image = 'images/sights/flint-mines-of-uchtut-in-navoi.jpg' WHERE id = 305;
UPDATE sights SET preview_image = 'images/sights/kara-kum-desert-in-navoi.jpg' WHERE id = 306;
UPDATE sights SET preview_image = 'images/sights/navoi-international-airport.jpg' WHERE id = 307;
UPDATE sights SET preview_image = 'images/sights/sardoba-malik-near-navoi.jpg' WHERE id = 308;
UPDATE sights SET preview_image = 'images/sights/sorrowful-mother-monument-in-navoi.jpg' WHERE id = 309;
UPDATE sights SET preview_image = 'images/sights/alisher-navoi-park-in-navoi.jpg' WHERE id = 310;
UPDATE sights SET preview_image = 'images/sights/monument-of-alisher-navoi-in-navoi.jpg' WHERE id = 311;
UPDATE sights SET preview_image = 'images/sights/cinema-uzbekistan-in-navoi.jpg' WHERE id = 312;
UPDATE sights SET preview_image = 'images/sights/palace-of-culture-farkhad-in-navoi.jpg' WHERE id = 313;
UPDATE sights SET preview_image = 'images/sights/palace-of-culture-shirin-in-navoi.jpg' WHERE id = 314;
UPDATE sights SET preview_image = 'images/events/zaamin1.jpg' WHERE id = 315;
UPDATE sights SET preview_image = 'images/events/Mausoleum-of-Saad-Ibn-Abu-Waqqas.jpg' WHERE id = 317;
UPDATE sights SET preview_image = 'images/sights/arnasay-reserve.jpg' WHERE id = 318;
UPDATE sights SET preview_image = 'images/sights/memorial-complex-of-sayd-ibn-abu-vakkos-in-jizzakh.jpg' WHERE id = 319;
UPDATE sights SET preview_image = 'images/events/baysun2.jpg' WHERE id = 320;
UPDATE sights SET preview_image = 'images/events/djarkuthan1.jpg' WHERE id = 321;
UPDATE sights SET preview_image = 'images/events/kampyrtepa2.jpg' WHERE id = 322;
UPDATE sights SET preview_image = 'images/events/denau.jpg' WHERE id = 323;
UPDATE sights SET preview_image = 'images/sights/Jarkurgan-minaret.jpg' WHERE id = 324;
UPDATE sights SET preview_image = 'images/sights/hakim-al-termezi-memorial-complex.jpg' WHERE id = 325;
UPDATE sights SET preview_image = 'images/sights/kokildor-ota-khanak.jpg' WHERE id = 326;
UPDATE sights SET preview_image = 'images/sights/sultan-saodat-complex-in-termez.jpg' WHERE id = 327;
UPDATE sights SET preview_image = 'images/sights/buddhist-stupa-zurmala-in-termez.jpg' WHERE id = 328;
UPDATE sights SET preview_image = 'images/sights/khalchayan-hillfort-in-termez.jpg' WHERE id = 329;
UPDATE sights SET preview_image = 'images/sights/sartepa-in-termez.jpg' WHERE id = 330;
UPDATE sights SET preview_image = 'images/sights/karatepa-and-fayastepa.jpg' WHERE id = 331;
UPDATE sights SET preview_image = 'images/Termez sights/Bridge-of-Friendship-Termez.jpg' WHERE id = 332;
UPDATE sights SET preview_image = 'images/Termez sights/Archeological-museum-in-museum.jpg' WHERE id = 335;
UPDATE sights SET preview_image = 'images/Termez sights/Dalverzintepa.jpg' WHERE id = 336;
UPDATE sights SET preview_image = 'images/Termez sights/kirk-kiz-fortress.jpg' WHERE id = 337;
UPDATE sights SET preview_image = 'images/sights/aral-sea-and-ustyurt-plateau.jpg' WHERE id = 338;
UPDATE sights SET preview_image = 'images/events/chilpak2.jpg' WHERE id = 339;
UPDATE sights SET preview_image = 'images/events/mizdahkan2.jpg' WHERE id = 340;
UPDATE sights SET preview_image = 'images/events/muynak2.jpg' WHERE id = 341;
UPDATE sights SET preview_image = 'images/events/uniqueness.jpg' WHERE id = 342;
UPDATE sights SET preview_image = 'images/events/ayaz–kala.jpg' WHERE id = 343;
UPDATE sights SET preview_image = 'images/sights/ayazkala-yurt-camp-in-karakalpakstan.jpg' WHERE id = 344;
UPDATE sights SET preview_image = 'images/sights/djanbas-kala-in-nukus.jpg' WHERE id = 345;
UPDATE sights SET preview_image = 'images/sights/renaissance-island-in-aral-sea.jpg' WHERE id = 346;
UPDATE sights SET preview_image = 'images/sights/national-museum-of-local-history-of-karakalpakstan.jpg' WHERE id = 347;
UPDATE sights SET preview_image = 'images/sights/visit-koi-krylgan-kala.jpg' WHERE id = 348;
UPDATE sights SET preview_image = 'images/sights/tuprak-kala-in-karakalpakstan.jpg' WHERE id = 349;
UPDATE sights SET preview_image = 'images/sights/museum-of-berdakh-in-karakalpakstan.jpg' WHERE id = 350;
UPDATE sights SET preview_image = 'images/sights/cave-towns-of-ustyurt.jpg' WHERE id = 351;
UPDATE sights SET preview_image = 'images/sights/chamoun-nabi-complex-in-karakalpakstan.jpg' WHERE id = 352;
UPDATE sights SET preview_image = 'images/sights/nukus-development-center-of-crafts.jpg' WHERE id = 353;
UPDATE sights SET preview_image = 'images/sights/guldursun-kala-in-karakalpakstan.jpg' WHERE id = 354;
UPDATE sights SET preview_image = 'images/sights/kumbaskan-kala-fortress-in-karakalpakstan.jpg' WHERE id = 355;
UPDATE sights SET preview_image = 'images/sights/kizil-kala-fortress-in-khoresm.jpg' WHERE id = 356;
UPDATE sights SET preview_image = 'images/sights/guyar-kala-fortress-in-karakalpakstan.jpg' WHERE id = 357;
UPDATE sights SET preview_image = 'images/sights/visit-barak-tam-settlement.jpg' WHERE id = 358;
UPDATE sights SET preview_image = 'images/sights/karakalpakstan-intangible-heritage.jpg' WHERE id = 359;
UPDATE sights SET preview_image = 'images/sights/butentau-in-karakalpakstan.jpg' WHERE id = 360;
UPDATE sights SET preview_image = 'images/sights/visit-kuyuk-kala-fortress.jpg' WHERE id = 361;
UPDATE sights SET preview_image = 'images/sights/petroglyphs-of-karakalpakstan.jpg' WHERE id = 362;
UPDATE sights SET preview_image = 'images/sights/visit-devkesken-wazir.jpg' WHERE id = 363;
UPDATE sights SET preview_image = 'images/sights/alan-kala-in-karakalpakstan.jpg' WHERE id = 364;
UPDATE sights SET preview_image = 'images/sights/the-complex-of-sultan-uwais-in-karakalpakstan.jpg' WHERE id = 365;
UPDATE sights SET preview_image = 'images/sights/visit-kungrad.jpg' WHERE id = 366;
UPDATE sights SET preview_image = 'images/sights/bibi-buvaida-mausoleum.jpg' WHERE id = 367;
UPDATE sights SET preview_image = 'images/sights/dakhma-yi-shahan.jpg' WHERE id = 368;
UPDATE sights SET preview_image = 'images/sights/khudayar-khan-fortress.jpg' WHERE id = 369;
UPDATE sights SET preview_image = 'images/sights/narbuta-biy-madrasah-in-kokand.jpg' WHERE id = 370;
UPDATE sights SET preview_image = 'images/sights/modari-khan-mausoleum-in-kokand.jpg' WHERE id = 371;
UPDATE sights SET preview_image = 'images/sights/legends-about-jami-mosque.jpg' WHERE id = 372;
UPDATE sights SET preview_image = 'images/sights/khamza-museum-house-in-kokand.jpg' WHERE id = 373;
UPDATE sights SET preview_image = 'images/sights/kamol-kazi-madrasah-in-kokand.jpg' WHERE id = 375;
UPDATE sights SET preview_image = 'images/sights/kokand-regional-studies-museum.jpg' WHERE id = 376;
UPDATE sights SET preview_image = 'images/sights/muvlon-buva-in-namangan.jpg' WHERE id = 377;
UPDATE sights SET preview_image = 'images/sights/chodak-village-in-namangan.jpg' WHERE id = 378;
UPDATE sights SET preview_image = 'images/sights/akhsikent-in-namangan.jpg' WHERE id = 379;
UPDATE sights SET preview_image = 'images/sights/hoja-amin-mausoleum-in-namangan.jpg' WHERE id = 380;
UPDATE sights SET preview_image = 'images/museums/Andijan-museum-of-local-history.jpg' WHERE id = 381;
UPDATE sights SET preview_image = 'images/museums/park-of-Babur-Andijan.jpg' WHERE id = 382;
UPDATE sights SET preview_image = 'images/museums/Babur-museum-Andijan.jpg' WHERE id = 383;
UPDATE sights SET preview_image = 'images/Urgench/Avesta-monument-of-Urgench.jpg' WHERE id = 384;
UPDATE sights SET preview_image = 'images/Urgench/monument-of-Jaloliddin-Manguberdi-in-Urgench.jpg' WHERE id = 385;
UPDATE sights SET preview_image = 'images/Urgench/youth-park-in-Urgench.jpg' WHERE id = 386;
UPDATE sights SET preview_image = 'images/Nukus/Kavat-Kala-fortress.jpg' WHERE id = 387;
