INSERT INTO translations (locale, column_name, value, translatable_id, translatable_type) VALUES
('ru', 'title', 'Афросиаб. Поселение древней страны востока.', 4, 'App\\Models\\Sight'),
('ru', 'title', 'Ургут', 5, 'App\\Models\\Sight'),
('ru', 'title', 'Площадь Регистан', 6, 'App\\Models\\Sight'),
('ru', 'title', 'Обсерватория Улугбека', 2, 'App\\Models\\Sight'),
('ru', 'title', 'Некрополь Шахи Зинда', 7, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Шер Дор', 8, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Тилля Кори', 9, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей пророка Даниила', 10, 'App\\Models\\Sight'),
('ru', 'title', 'Мечеть Биби-Ханым', 1, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Гур-Эмир', 11, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Рухабад', 12, 'App\\Models\\Sight'),
('ru', 'title', 'Самаркандская бумажная фабрика', 13, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Улугбека', 14, 'App\\Models\\Sight'),
('ru', 'title', 'Фабрика шелковых ковров \"Худжум\"', 15, 'App\\Models\\Sight'),
('ru', 'title', 'Ансамбль Абди Дарун', 18, 'App\\Models\\Sight'),
('ru', 'title', 'Базар Сиаб', 16, 'App\\Models\\Sight'),
('ru', 'title', 'Неосязаемое наследие Самарканда', 20, 'App\\Models\\Sight'),
('ru', 'title', 'Католическая церковь Святого Иоанна Крестителя', 21, 'App\\Models\\Sight'),
('ru', 'title', 'Гиждуван', 44, 'App\\Models\\Sight'),
('ru', 'title', 'Варахша, древнее городище', 45, 'App\\Models\\Sight'),
('ru', 'title', 'Древний городище Варданзи', 46, 'App\\Models\\Sight'),
('ru', 'title', 'Городище Пайкенд', 47, 'App\\Models\\Sight'),
('ru', 'title', 'Шафиркан', 48, 'App\\Models\\Sight'),
('ru', 'title', 'Дворец Ситораи Мохи Хоса', 50, 'App\\Models\\Sight'),
('ru', 'title', 'Ворота Талипач', 51, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Болохауз', 52, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Сайфад-Дин Бохарзи', 53, 'App\\Models\\Sight'),
('ru', 'title', 'Ляби-Хауз', 39, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Ходжа Зайнутдин', 43, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Бахоуддина Накшбанди', 40, 'App\\Models\\Sight'),
('ru', 'title', 'Караван-сарай Нугай', 38, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Надир Диванбеги', 54, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Мири-Араб', 55, 'App\\Models\\Sight'),
('ru', 'title', 'Крепость Арк', 56, 'App\\Models\\Sight'),
('ru', 'title', 'Минарет Калян', 49, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Чор-Минор', 57, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Амира Алим-хана', 58, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Саманидов', 36, 'App\\Models\\Sight'),
('ru', 'title', 'Экоцентр Джейран', 37, 'App\\Models\\Sight'),
('ru', 'title', 'Минарет Вабкента', 41, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Абдулазиз', 59, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Халифа Худойдода', 60, 'App\\Models\\Sight'),
('ru', 'title', 'Мечеть Магоки Аттари', 61, 'App\\Models\\Sight'),
('ru', 'title', 'Источник святого Иова', 62, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Улугбека', 42, 'App\\Models\\Sight'),
('ru', 'title', 'Усыпальница Сайида Амира Кулала', 65, 'App\\Models\\Sight'),
('ru', 'title', 'Мечеть Курпа', 66, 'App\\Models\\Sight'),
('ru', 'title', 'Центральный рынок в Бухаре', 67, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Буян Кули Хана', 68, 'App\\Models\\Sight'),
('ru', 'title', 'Подземная тюрьма Эмира', 64, 'App\\Models\\Sight'),
('ru', 'title', 'Уструшана', 69, 'App\\Models\\Sight'),
('ru', 'title', 'Захоронение Шейха Ахбор Вали', 70, 'App\\Models\\Sight'),
('ru', 'title', 'Искусство миниатюр Бухары', 71, 'App\\Models\\Sight'),
('ru', 'title', 'Бухарские ковры', 72, 'App\\Models\\Sight'),
('ru', 'title', 'Неосязаемое наследие Бухары', 73, 'App\\Models\\Sight'),
('ru', 'title', 'Топрак кала в Хиве.', 210, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей шейха Сайеда Алауддина в Хиве', 200, 'App\\Models\\Sight'),
('ru', 'title', 'Цитадель Куня Арк в Хиве', 201, 'App\\Models\\Sight'),
('ru', 'title', 'Крепость Ичан-Кала в  Хиве', 202, 'App\\Models\\Sight'),
('ru', 'title', 'Дворец Нуруллабая в Хиве', 205, 'App\\Models\\Sight'),
('ru', 'title', 'Ак-мечеть в Хиве', 215, 'App\\Models\\Sight'),
('ru', 'title', 'Дворец Чадрахавли в Хиве', 197, 'App\\Models\\Sight'),
('ru', 'title', 'Ислам Ходжа Минарет в Хиве', 211, 'App\\Models\\Sight'),
('ru', 'title', 'Минарет Кальта минар в Хиве', 216, 'App\\Models\\Sight'),
('ru', 'title', 'Дворец ТашХоули в Хиве', 217, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе араб Мухаммад-хан в Хиве', 218, 'App\\Models\\Sight'),
('ru', 'title', 'Караван-сарай Алла-Кули-хан в Хиве', 209, 'App\\Models\\Sight'),
('ru', 'title', 'Биканжан-Бика в Хиве', 207, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Пахлаван Махмуд, медресе и минарет в Хиве', 213, 'App\\Models\\Sight'),
('ru', 'title', 'Кази Калян Медресе в Хиве', 194, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Атаджан в Хиве', 195, 'App\\Models\\Sight'),
('ru', 'title', 'Саид Мухаммад Хан медресе в Хиве', 219, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Саид Нияз в Хиве', 198, 'App\\Models\\Sight'),
('ru', 'title', 'Джума-мечеть в Хиве', 203, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Махдум Талиба в Хиве', 206, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Кутлуг Мурад в Хиве', 208, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Абд Аль Бобо', 199, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Шейха Каландар Бобо', 196, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Мухаммад Амина', 212, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Мазари Шариф', 214, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Мухаммад Рахим хана', 220, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Юсуфа Ясулбаши', 223, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Паяндо', 224, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Матпанабай', 221, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Матнияз Диванбеги', 225, 'App\\Models\\Sight'),
('ru', 'title', 'Мечеть Хассан Мурат Кушбеги', 226, 'App\\Models\\Sight'),
('ru', 'title', 'Дишан Кала', 227, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе  Шираз хана', 193, 'App\\Models\\Sight'),
('ru', 'title', 'Мечеть Яр Мухаммад  Девон', 228, 'App\\Models\\Sight'),
('ru', 'title', 'Мечеть Багданли', 222, 'App\\Models\\Sight'),
('ru', 'title', 'Базар старой Хивы', 229, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Палван Кари', 230, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Шахимардан', 231, 'App\\Models\\Sight'),
('ru', 'title', 'Мечеть Шейха Мухтар Ата', 232, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Мамад Марам', 233, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Торт Шаффаз', 234, 'App\\Models\\Sight'),
('ru', 'title', 'Медресе Рафанек', 235, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей трех святых', 236, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Биби Хажар', 237, 'App\\Models\\Sight'),
('ru', 'title', 'Минарет Саид бая', 238, 'App\\Models\\Sight'),
('ru', 'title', 'Зороастрийское наследие Хорезма', 239, 'App\\Models\\Sight'),
('ru', 'title', 'Комплекс Аиртам', 240, 'App\\Models\\Sight'),
('ru', 'title', 'Мавзолей Саид Мухаммад Махира', 241, 'App\\Models\\Sight'),
('ru', 'title', 'Восточный базар в Хиве', 242, 'App\\Models\\Sight'),
('ru', 'title', 'Кибла Тозабог', 243, 'App\\Models\\Sight'),
('ru', 'title', 'Уникальная архитектурная эпиграфика Хивы', 245, 'App\\Models\\Sight'),
('ru', 'title', 'Ювелирное дело Хивы', 246, 'App\\Models\\Sight'),
('ru', 'title', 'Керамика Хивы', 247, 'App\\Models\\Sight'),
('ru', 'title', 'Музей истории Хорезма', 248, 'App\\Models\\Sight'),
('ru', 'title', 'Крепость Хазарасп', 249, 'App\\Models\\Sight');